# Generated by Django 2.1 on 2018-09-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='Ссылка')),
                ('description', models.TextField(max_length=140, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('price', models.SmallIntegerField(verbose_name='Цена')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
                ('description', models.TextField(max_length=140, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('price', models.SmallIntegerField(verbose_name='Цена')),
                ('status', models.IntegerField(choices=[(1, 'Доступно'), (0, 'Недоступно'), (2, 'Ожидается')], default=1, verbose_name='Статус')),
                ('update', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name',)},
        ),
    ]
