# Generated by Django 2.1 on 2018-09-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='Решение')),
                ('pubdate', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Новый заказ'), (1, 'Ожидает предоплаты'), (2, 'Выполняется'), (3, 'Ожидает оплаты'), (4, 'Завершён'), (5, 'Отменён'), (6, 'Отклонено')], default=0, verbose_name='Статус')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('update', 'pubdate'),
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма')),
                ('terminal', models.TextField(verbose_name='Терминал')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Выписка',
                'verbose_name_plural': 'Выписки',
                'ordering': ('date',),
            },
        ),
    ]
